apiVersion: v1
entries:
  falkordb-browser:
  - apiVersion: v2
    appVersion: 1.7.2
    created: "2026-02-16T13:04:58.123749237Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 4a651fce827c0a1ffa0c25ced0af2e231fefaa6a3e2fa8d56e964fc82f48e684
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.2.tgz
    version: 1.7.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2026-02-16T13:04:58.123190105Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 26067d9c13dfcd615cd79217f8af16d4e07c6637162a86c84c7befa577243941
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.1.tgz
    version: 1.7.1
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2026-02-16T13:04:58.122618258Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: b8658a2514760a9239c59dc7b8dec3094122ab39ce92a9beacb82f0befbd9c1c
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.0.tgz
    version: 1.7.0
  - apiVersion: v2
    appVersion: 1.6.7
    created: "2026-02-16T13:04:58.121990336Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: aa4d05e9cf908bbb06139112b611a46e222c284270f40038b7c3381590d7b3d2
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.6.7.tgz
    version: 1.6.7
generated: "2026-02-16T13:04:58.121241846Z"
