apiVersion: v1
entries:
  falkordb-browser:
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2026-01-28T10:55:09.59732781Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: b8658a2514760a9239c59dc7b8dec3094122ab39ce92a9beacb82f0befbd9c1c
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.0.tgz
    version: 1.7.0
  - apiVersion: v2
    appVersion: 1.6.7
    created: "2026-01-28T10:55:09.596726798Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: aa4d05e9cf908bbb06139112b611a46e222c284270f40038b7c3381590d7b3d2
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.6.7.tgz
    version: 1.6.7
generated: "2026-01-28T10:55:09.595994759Z"
